version: "3.3"
services:
    # db:

    api:
        build: 
            context: ./api
            dockerfile: api.dockerfile
        ports:
            - "3000:3000"
        volumes:
            - "./api:/usr/src/app"
        # command: sh -c "while true; do sleep 1; done"
        

    #app: